[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info"

[theme]
primaryColor = "#3B4B5C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
